### ISSUE TITLE
Error when running `python examples/example_cluster_sample.py`

### ISSUE THREAD

**Issue by zhangbaozhe** [hubernikus/fast_obstacle_avoidance#2]
When I try to run the provided example code in the project directory `python examples/example_cluster_sample.py`, I get a ImportError. It says that cannot import name 'get_intersection_with_circle' from 'vartools.math'. And I have checked the file `src/various_tools/src/vartools/math.py` and I did not find that function.

**Comment by hubernikus** [comment]
The submodules were indeed not updated. This is now fixed. Please try pulling the latest version of the packages in the 'src' folder, and rerun the setup instructions.

**Comment by zhangbaozhe** [comment]
Thanks for the quick response. I have pulled the latest version. The `ImportError` now is gone, but it raises some other errors. I use miniconda for my Python environment and tested the example file with python3.9.16. Here is the error message when I try to run the example. 
```
Traceback (most recent call last):
  File "/home/baozhe/FastLab/fast_obstacle_avoidance/examples/example_cluster_sample.py", line 9, in <module>
    from vartools.states import ObjectPose
  File "/home/baozhe/FastLab/fast_obstacle_avoidance/src/various_tools/vartools/states.py", line 27, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
```

I have also tested with python3.10. The file can run, but the GUI stays blank and the console keeps telling me there is a runtime warning.

**Comment by hubernikus** [comment]
dataclass with slots are used in some of the libraries, this is a feature introduced in python3.10. 

Make sure that the 'saving' of the animation is deactivated, otherwise, it just saves them into the figure folder rather than visualize it.

Can you tell me the warning that you get with python3.10?

**Comment by zhangbaozhe** [comment]
I re-tried using python3.10. Now the GUI is OK. The warning message is 
```
/home/baozhe/miniconda3/envs/fast_obstacle_avoidance/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
```

**Comment by hubernikus** [comment]
Ok. That seems to be related to the shapely library, which is used to simulate the laserscan. It should not affect the implementation if you use your sensor reading.
